In [1]:
6

6

In [3]:
x = 3
print(x,type(x))

3 <class 'int'>


In [4]:
print(x**2)

9


In [5]:
s ='hello'
print(s,len(s))

hello 5


In [7]:
w = 'world'
co = s+''+w
print(co)

helloworld


In [9]:
l =[2,8,4,5,7]
print(l,l[-1])

[2, 8, 4, 5, 7] 7


In [10]:
nums = list(range(5))
nums[2:4] = [8,9]
print(nums)

[0, 1, 8, 9, 4]


In [11]:

for e in l:
    print(e)

2
8
4
5
7


In [13]:
# enumerate
for idx,e in enumerate(l):
    print('#%d:%s' %(idx + 1,e))

#1:2
#2:8
#3:4
#4:5
#5:7


In [14]:
squar = []
for s in l:
    squar.append(s**2)
    print(squar)

[4]
[4, 64]
[4, 64, 16]
[4, 64, 16, 25]
[4, 64, 16, 25, 49]


In [16]:
# disnoris
d = {'cat': 'cute','dog':'furry'}
print(d['cat'])
print('cat'in d)

cute
True


In [17]:
d['fish'] = 'wet'
print(d['fish'])

wet


In [24]:
d = {'person':'2','cat':'4','spider':'8'}
for animal in d:
    legs = d[animal]
    print('A %s has D leg', (animal,legs))

A %s has D leg ('person', '2')
A %s has D leg ('cat', '4')
A %s has D leg ('spider', '8')


In [25]:
def add_number(a,b):
    return(a+b)
print(add_number(3,5))

8


In [26]:
import numpy as np

In [28]:
import pandas as pd

In [29]:
import matplotlib.pyplot as plt

In [30]:
my_list = [1,2,3]

In [31]:
my_list

[1, 2, 3]

In [34]:
np.array(my_list)

array([1, 2, 3])

In [96]:
my_matrix = [[1,2,3],[4,5,6],[6,7,8]]
my_matrix

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [97]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [39]:
# gnerate number in rane using array
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

another varient with the step size mentioned

In [42]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
np.zeros(2) # single dimensonal 

array([ 0.,  0.])

In [47]:
np.zeros((2,2)) 

array([[ 0.,  0.],
       [ 0.,  0.]])

In [48]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [50]:
np.ones((2,2))*6

array([[ 6.,  6.],
       [ 6.,  6.]])

In [52]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

In [53]:
# identity matrix
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

generate random number np.random.rand()

In [54]:
np.random.rand(4)

array([ 0.41310787,  0.92394168,  0.78237438,  0.13075312])

In [55]:
np.random.rand(0)

array([], dtype=float64)

multi dimensional example


In [56]:
np.random.rand(3,3)

array([[ 0.99113631,  0.05044739,  0.2129818 ],
       [ 0.47915378,  0.09004207,  0.92696868],
       [ 0.05438576,  0.18031325,  0.43950398]])

returns a random integer fron specific range

In [59]:
np.random.randint(99,100)

99

more than one random number

In [60]:
np.random.randint(1,100,10)

array([91, 56, 92, 89, 95, 11, 85, 62, 69, 48])

In [93]:
arr = np.arange(25)
ranar = np.random.randint(1,100,10)

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [94]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
ranar

array([19, 96, 92, 29, 63, 27, 40, 84, 53, 31])

In [72]:
ranar.max()

96

In [73]:
arr.max()

24

In [76]:
ranar.argmax() # return position having maximum value

1

In [80]:
ranar.shape

(10,)

In [82]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [84]:
arr.reshape(25,1).shape

(25, 1)

In [85]:
np.zeros(0).dtype

dtype('float64')

In [86]:
arr = np.arange(0,11)

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
 w=arr.copy()
w

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
arr_2d= np.array(my_matrix)

In [101]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [113]:
arr_2d[:,:2]

array([[1, 2],
       [4, 5],
       [6, 7]])

SyntaxError: invalid syntax (<ipython-input-114-e51d0b52bdf7>, line 1)